# Generated by Django 5.0.1 on 2025-01-30 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("date_created", models.DateTimeField(auto_now=True)),
                ("date_modified", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField()),
                ("bio", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("year", models.IntegerField()),
                ("isbn", models.CharField(max_length=10)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myfirstapp.author",
                    ),
                ),
            ],
        ),
    ]
