# Generated by Django 5.0.1 on 2025-01-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myfirstapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.TextField(default="Scifi"),
        ),
        migrations.AddField(
            model_name="book",
            name="num_pages",
            field=models.IntegerField(null=True),
        ),
    ]
