# Generated by Django 5.1.5 on 2025-01-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('isbn', models.CharField(max_length=10)),
            ],
        ),
    ]
