# Generated by Django 5.1.5 on 2025-01-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0003_alter_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.TextField(default='SciFi'),
        ),
        migrations.AddField(
            model_name='book',
            name='page_conut',
            field=models.IntegerField(null=True),
        ),
    ]
