# Generated by Django 5.1.5 on 2025-02-11 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_ordered', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheese', models.IntegerField(choices=[(0, 'Mozzarella'), (1, 'Vegan'), (2, 'Low Fat'), (3, 'None (plain)')])),
                ('order_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzaApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.IntegerField(choices=[(0, 'Normal'), (1, 'Thin'), (2, 'Thick'), (3, 'Gluten Free'), (4, 'Vegan')])),
                ('order_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzaApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('address3', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('card_name', models.CharField(max_length=200)),
                ('card_number', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=4)),
                ('expire', models.DateField()),
                ('order_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzaApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sauce', models.IntegerField(choices=[(0, 'Tomato'), (1, 'BBQ'), (2, 'Pesto')])),
                ('order_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzaApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Large'), (3, 'X-Large')])),
                ('order_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzaApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.IntegerField(choices=[(0, 'Pepperoni'), (1, 'Chicken'), (2, 'Ham'), (3, 'Pineapple'), (4, 'Peppers'), (5, 'Mushrooms'), (6, 'Onions'), (7, 'Sweetcorn')])),
                ('order_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzaApp.order')),
            ],
        ),
    ]
