# Generated by Django 5.1.5 on 2025-02-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0002_remove_base_base_remove_base_order_det_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expire',
            field=models.CharField(max_length=7),
        ),
    ]
