# Generated by Django 5.1.5 on 2025-02-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0003_alter_payment_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expire',
            field=models.CharField(default='MM/YYYY', max_length=7),
        ),
    ]
