# Generated by Django 5.1.5 on 2025-02-12 17:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0005_orderdetails_person_alter_payment_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pizzaApp.orderdetails'),
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='order',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='time_ordered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
